# Generated by Django 4.2.7 on 2024-03-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_koloda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('лицо', models.CharField(max_length=200)),
                ('изнанка', models.TextField()),
                ('koloda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.koloda')),
            ],
        ),
    ]
